"""Removed context from activity log

Revision ID: 180f20b75286
Revises: 2edadacbf682
Create Date: 2025-05-14 12:52:56.869556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180f20b75286'
down_revision: Union[str, None] = '2edadacbf682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_log', 'context')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_log', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
