"""added pm user permission

Revision ID: 1dd63645fcc3
Revises: ac6a92ad8604
Create Date: 2025-04-24 11:39:12.510836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd63645fcc3'
down_revision: Union[str, None] = 'ac6a92ad8604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_users', 'labels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_users', sa.Column('labels', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
