"""Added an active boolean for logic deletions, to avoid fk constraints when deleting stuff

Revision ID: 27b445ba7bb7
Revises: 180f20b75286
Create Date: 2025-05-15 13:05:00.743467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b445ba7bb7'
down_revision: Union[str, None] = '180f20b75286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microtasks', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'active')
    op.drop_column('projects', 'active')
    op.drop_column('microtasks', 'active')
    # ### end Alembic commands ###
