"""Added logical delete to ProjectsUser Relation

Revision ID: a4eb5497bb0d
Revises: 0ec3ed01151b
Create Date: 2025-06-11 13:02:20.861599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4eb5497bb0d'
down_revision: Union[str, None] = '0ec3ed01151b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_users', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE projects_users SET active = true")
    
    # 3. Finally set the column to non-nullable
    op.alter_column('projects_users', 'active',
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text('true')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_users', 'active')
    # ### end Alembic commands ###
