"""Changes on ORM models structure and adding Bidirectional relationships for backpopulate

Revision ID: fdf339bbd030
Revises: d216e4fea6f5
Create Date: 2025-04-06 20:34:50.631789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf339bbd030'
down_revision: Union[str, None] = 'd216e4fea6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('personal_chats')]
    if 'project_id' not in columns:
        op.add_column('personal_chats', sa.Column('project_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'personal_chats', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_chats', type_='foreignkey')
    op.drop_column('personal_chats', 'project_id')
    # ### end Alembic commands ###
